owner_address = "c4228701A7B92793b2428687DC37D0ed92e0d7A7"
owner_private_key = "$PRIVATE_KEY"
contract_address = "c4228701A7B92793b2428687DC37D0ed92e0d7A7"

log_level = "trace"
subgraph_url = "https://api.thegraph.com/subgraphs/name/juanmardefago/block-oracle"
# FIXME: Once we have access to the Epoch Manager, we can completely remove this entry from configuration.
# Should be about 10 minutes in Goerli
epoch_duration = 40

[protocol_chain]
name = "goerli:0"
jrpc = "$GOERLI_0"
# HOTFIX: emulates a 15 minute epoch duration
# FIXME: Once we have access to the Epoch Manager, this value should be something around 30 seconds.
polling_interval_in_seconds = 900

[indexed_chains]
"arbitrum:0" = "$ARBITRUM_0"
"arbitrum:one" = "$ARBITRUM_ONE"
"avalnche:0" = "$AVALNCHE_0"
"boba:0" = "$BOBA_0"
"clover:0" = "$CLOVER_0"
"fantom:0" = "$FANTOM_0"
"fuji:0" = "$FUJI_0"
"fuse:0" = "$FUSE_0"
"kovan:1" = "$KOVAN_1"
"mainnet:0" = "$MAINNET_0"
"matic:0" = "$MATIC_0"
"mbase:montreal" = "$MBASE_MONTREAL"
"mbase:netherlands" = "$MBASE_NETHERLANDS"
"moonbeam:montreal" = "$MOONBEAM_MONTREAL"
"mumbai:0" = "$MUMBAI_0"
"optimism:0" = "$OPTIMISM_0"
"optimism:kovan" = "$OPTIMISM_KOVAN"
"poacore:0" = "$POACORE_0"
"poasokol:0" = "$POASOKOL_0"
"rinkeby:0" = "$RINKEBY_0"
"ropsten:0" = "$ROPSTEN_0"
"xdai:0" = "$XDAI_0"
"zksync:0" = "$ZKSYNC_0"

# "aurora:testnet"
# "binance:ankr"
# "celo:0"
# "celo:alfajores"
# "chapel:0"
# "moonrivr:0"
