[package]
name = "oracle-encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
epoch-encoding = { path = "../encoding" }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
