owner_address = "0xfA711DA0f9336f27E7B7483398cbd8F0880f259a"
owner_private_key = "$PRIVATE_KEY"
epoch_manager_address = "0x03541c5cd35953CD447261122F93A5E7b812D697"
data_edge_address = "0xc4228701A7B92793b2428687DC37D0ed92e0d7A7"
log_level = "trace"
subgraph_url = "https://api.thegraph.com/subgraphs/name/juanmardefago/block-oracle"
bearer_token = "TODO"
protocol_chain_polling_interval_in_seconds = 30

[protocol_chain]
name = "goerli:0"
jrpc = "$GOERLI_0"
polling_interval_in_seconds = 30

[indexed_chains]
"arbitrum:0" = "$ARBITRUM_0"
"arbitrum:one" = "$ARBITRUM_ONE"
"aurora:testnet" = "$AURORA_TESTNET"
"avalnche:0" = "$AVALNCHE_0"
"binance:0" = "$BINANCE_0"
"boba:0" = "$BOBA_0"
"chapel:0" = "$CHAPEL_0"
"clover:0" = "$CLOVER_0"
"fantom:0" = "$FANTOM_0"
"fuji:0" = "$FUJI_0"
"fuse:0" = "$FUSE_0"
"kovan:1" = "$KOVAN_1"
"mainnet:0" = "$MAINNET_0"
"matic:0" = "$MATIC_0"
"mbase:montreal" = "$MBASE_MONTREAL"
"mbase:netherlands" = "$MBASE_NETHERLANDS"
"moonbeam:montreal" = "$MOONBEAM_MONTREAL"
"moonrivr:0" = "$MOONRIVR_0"
"mumbai:0" = "$MUMBAI_0"
"optimism:0" = "$OPTIMISM_0"
"optimism:kovan" = "$OPTIMISM_KOVAN"
"poacore:0" = "$POACORE_0"
"poasokol:0" = "$POASOKOL_0"
"rinkeby:0" = "$RINKEBY_0"
"ropsten:0" = "$ROPSTEN_0"
"xdai:0" = "$XDAI_0"
"zksync:0" = "$ZKSYNC_0"
