steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/block-oracle:latest", "-f", "k8s/Dockerfile", "."]

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/block-oracle:latest"]

  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./k8s/block-oracle.deployment.yaml
  - "--image=gcr.io/$PROJECT_ID/block-oracle:latest"
  - --location=us-central1-a
  - --cluster=epoch-block-oracle
timeout: "3200s"
options:
  machineType: "E2_HIGHCPU_8"
