owner_address = "FOO"
contract_address = "BAR"

protocol_chain_polling_interval_in_seconds = 120

[protocol_chain]
name = "eip155:1"
jrpc = "https://example.com"

[indexed_chains]
"spam:42" = "https://example.com"
