[package]
name = "block-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
envconfig = "0.10.0"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "migrate"] }

[dev-dependencies]
epoch-encoding = { path = "../encoding" }
