global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: block-oracle
    static_configs:
      - targets: ["block-oracle:9090"]
