[package]
name = "json-oracle-encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
epoch-encoding = { path = "../encoding" }
ethabi = "17.2.0"
hex = "0.4.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1"
