[package]
name = "epoch-encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
tiny-keccak = { version = "2.0", features = ["keccak"] }

[dev-dependencies]
tokio = { version = "1.14", features = ["sync", "parking_lot", "rt", "macros"] }
never = "0.1.0"
